app = "openbox-db"
primary_region = "gru"

[build]
  image = "pgvector/pgvector:pg16"

[env]
  POSTGRES_DB = "openbox"
  POSTGRES_USER = "postgres"
  PGDATA = "/var/lib/postgresql/data/pgdata"

[mounts]
  source = "pgdata"
  destination = "/var/lib/postgresql/data"
